from django.urls import path
from .views import (
    register,
    verify_register,
    set_password,
    login_view,
    otp_login,
    otp_verify,
    complete_profile,
    LogoutView,
    MainLogoutView,

    admin_dashboard,
    UserListView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    StoryListView,
    StoryCreateView,
    StoryDeleteView,
    PosterListView,
    PosterCreateView,
    PosterDeleteView,
    CommentListView,
    CommentCreateView,
    CommentDeleteView,
    FAQListView,
    FAQCreateView,
    FAQDeleteView,
    AchievementListView,
    AchievementCreateView,
    AchievementUpdateView,
    AchievementDeleteView,
    LiveEventListView,
    LiveEventCreateView,
    LiveEventUpdateView,
    LiveEventDeleteView,
    PackageListView,
    PackageCreateView,
    PackageUpdateView,
    PackageDeleteView,

    PlansIntroductionCreateView,
    PlansIntroductionUpdateView,
    DataIntroductionCreateView,
    DataIntroductionUpdateView,
    CounselingIntroductionCreateView,
    CounselingIntroductionUpdateView,
    EstimationIntroductionCreateView,
    EstimationIntroductionUpdateView,
    ChoiceIntroductionCreateView,
    ChoiceIntroductionUpdateView,
    LiveIntroductionCreateView,
    LiveIntroductionUpdateView,
    AboutUsIntroductionCreateView,
    AboutUsIntroductionUpdateView,
    AllPaymentListView,
    MediaListView,
    MediaCreateView,
    MediaUpdateView,
    MediaDeleteView,
    RankBankListView,
    RankBankCreateView,
    RankBankUpdateView,
    RankBankDeleteView,
    RuleListView,
    RuleCreateView,
    RuleUpdateView,
    RuleDeleteView,
    StaticMessageListView,
    StaticMessageCreateView,
    StaticMessageUpdateView,
    StaticMessageDeleteView,

    consultant_dashboard,
    ConsultantCreateView,
    ConsultantUpdateView,
    ConsultantScheduleListView,
    ConsultantScheduleCreateView,
    ConsultantScheduleDeleteView,
    MyStudentListView,

    student_dashboard,
    PaymentListView,
    rank_form,
    personality60,
    validity,
)

urlpatterns = [
    path("register/", register, name="register"),
    path("verify-register/", verify_register, name="verify-register"),
    path("set-password/", set_password, name="set-password"),
    path("login/", login_view, name="login"),
    path("otp-login/", otp_login, name="otp-login"),
    path("otp-verify/", otp_verify, name="otp-verify"),
    path("complete-profile/", complete_profile, name="complete-profile"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("main-logout/", MainLogoutView.as_view(), name="main_logout"),

    path("admins/dashboard/", admin_dashboard, name="admin_dashboard"),

    path("admins/users/", UserListView.as_view(), name="user_list"),
    path("admins/users/add/", UserCreateView.as_view(), name="user_add"),
    path("admins/users/<int:pk>/edit/", UserUpdateView.as_view(), name="user_edit"),
    path("admins/users/<int:pk>/delete/", UserDeleteView.as_view(), name="user_delete"),

    path("admins/stories/", StoryListView.as_view(), name="story_list"),
    path("admins/stories/add/", StoryCreateView.as_view(), name="story_add"),
    path("admins/stories/<int:pk>/delete/", StoryDeleteView.as_view(), name="story_delete"),

    path("admins/posters/", PosterListView.as_view(), name="poster_list"),
    path("admins/posters/add/", PosterCreateView.as_view(), name="poster_add"),
    path("admins/posters/<int:pk>/delete/", PosterDeleteView.as_view(), name="poster_delete"),

    path("admins/comments/", CommentListView.as_view(), name="comment_list"),
    path("admins/comments/add/", CommentCreateView.as_view(), name="comment_add"),
    path("admins/comments/<int:pk>/delete/", CommentDeleteView.as_view(), name="comment_delete"),

    path("admins/faqs/", FAQListView.as_view(), name="faq_list"),
    path("admins/faqs/add/", FAQCreateView.as_view(), name="faq_add"),
    path("admins/faqs/<int:pk>/delete/", FAQDeleteView.as_view(), name="faq_delete"),

    path("admins/achievements/", AchievementListView.as_view(), name="achievement_list"),
    path("admins/achievements/add/", AchievementCreateView.as_view(), name="achievement_add"),
    path("admins/achievements/<int:pk>/edit/", AchievementUpdateView.as_view(), name="achievement_edit"),
    path("admins/achievements/<int:pk>/delete/", AchievementDeleteView.as_view(), name="achievement_delete"),

    path("admins/live-events/", LiveEventListView.as_view(), name="live_event_list"),
    path("admins/live-events/add/", LiveEventCreateView.as_view(), name="live_event_add"),
    path("admins/live-events/<int:pk>/edit/", LiveEventUpdateView.as_view(), name="live_event_edit"),
    path("admins/live-events/<int:pk>/delete/", LiveEventDeleteView.as_view(), name="live_event_delete"),

    path("admins/packages/", PackageListView.as_view(), name="package_list"),
    path("admins/packages/add/", PackageCreateView.as_view(), name="package_add"),
    path("admins/packages/<int:pk>/edit/", PackageUpdateView.as_view(), name="package_edit"),
    path("admins/packages/<int:pk>/delete/", PackageDeleteView.as_view(), name="package_delete"),

    path("admins/plans-introduction/create/", PlansIntroductionCreateView.as_view(), name="plans-introduction-create"),
    path("admins/plans-introduction/<int:pk>/edit/", PlansIntroductionUpdateView.as_view(),name="plans-introduction-update"),

    path("admins/data-introduction/create/", DataIntroductionCreateView.as_view(), name="data-introduction-create"),
    path("admins/data-introduction/<int:pk>/edit/", DataIntroductionUpdateView.as_view(),name="data-introduction-update"),

    path("admins/counseling-introduction/create/", CounselingIntroductionCreateView.as_view(), name="counseling-introduction-create"),
    path("admins/counseling-introduction/<int:pk>/edit/", CounselingIntroductionUpdateView.as_view(), name="counseling-introduction-update"),

    path("admins/estimation-introduction/create/", EstimationIntroductionCreateView.as_view(), name="estimation-introduction-create"),
    path("admins/estimation-introduction/<int:pk>/edit/", EstimationIntroductionUpdateView.as_view(), name="estimation-introduction-update"),

    path("admins/choice-introduction/create/", ChoiceIntroductionCreateView.as_view(), name="choice-introduction-create"),
    path("admins/choice-introduction/<int:pk>/edit/", ChoiceIntroductionUpdateView.as_view(), name="choice-introduction-update"),

    path("admins/live-introduction/create/", LiveIntroductionCreateView.as_view(), name="live-introduction-create"),
    path("admins/live-introduction/<int:pk>/edit/", LiveIntroductionUpdateView.as_view(), name="live-introduction-update"),

    path("admins/about-introduction/create/", AboutUsIntroductionCreateView.as_view(), name="about-introduction-create"),
    path("admins/about-introduction/<int:pk>/edit/", AboutUsIntroductionUpdateView.as_view(), name="about-introduction-update"),

    path("admins/payments/", AllPaymentListView.as_view(), name="all_payment_list"),

    path("admins/medias/", MediaListView.as_view(), name="media_list"),
    path("admins/medias/add/", MediaCreateView.as_view(), name="media_add"),
    path("admins/medias/<int:pk>/edit/", MediaUpdateView.as_view(), name="media_edit"),
    path("admins/medias/<int:pk>/delete/", MediaDeleteView.as_view(), name="media_delete"),

    path("admins/rank-banks/", RankBankListView.as_view(), name="rank_bank_list"),
    path("admins/rank-banks/add/", RankBankCreateView.as_view(), name="rank_bank_add"),
    path("admins/rank-banks/<int:pk>/edit/", RankBankUpdateView.as_view(), name="rank_bank_edit"),
    path("admins/rank-banks/<int:pk>/delete/", RankBankDeleteView.as_view(), name="rank_bank_delete"),

    path("admins/rules/", RuleListView.as_view(), name="rule_list"),
    path("admins/rules/add/", RuleCreateView.as_view(), name="rule_add"),
    path("admins/rules/<int:pk>/edit/", RuleUpdateView.as_view(), name="rule_edit"),
    path("admins/rules/<int:pk>/delete/", RuleDeleteView.as_view(), name="rule_delete"),

    path("admins/static-messages/", StaticMessageListView.as_view(), name="static_message_list"),
    path("admins/static-messages/add/", StaticMessageCreateView.as_view(), name="static_message_add"),
    path("admins/static-messages/<int:pk>/edit/", StaticMessageUpdateView.as_view(), name="static_message_edit"),
    path("admins/static-messages/<int:pk>/delete/", StaticMessageDeleteView.as_view(), name="static_message_delete"),

    path("consultants/dashboard/", consultant_dashboard, name="consultant_dashboard"),

    path("consultants/consultant/add/", ConsultantCreateView.as_view(), name="consultant_add"),
    path("consultants/consultant/<int:pk>/edit/", ConsultantUpdateView.as_view(), name="consultant_edit"),

    path("consultants/schedules/", ConsultantScheduleListView.as_view(), name="schedule_list"),
    path("consultants/schedules/add/", ConsultantScheduleCreateView.as_view(), name="schedule_add"),
    path("consultants/schedules/<int:pk>/delete/", ConsultantScheduleDeleteView.as_view(), name="schedule_delete"),

    path("consultants/my-students/", MyStudentListView.as_view(), name="my_student_list"),

    path("students/dashboard/", student_dashboard, name="student_dashboard"),

    path("students/payments/", PaymentListView.as_view(), name="payment_list"),
    path("students/personality/", personality60, name="personality60"),
    path("students/rank/", rank_form, name="rank_form"),
    path("students/validity/", validity, name="validity"),
]