# Generated by Django 6.0.5 on 2026-07-23 14:09

import django.db.models.deletion
import django_ckeditor_5.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_consultantschedule_is_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'جلسه فردی با دکتر نایب زاده'), ('2', 'جلسه فردی با مشاور'), ('3', 'تحلیل شخصیت'), ('4', 'تعیین شانس قبولی'), ('5', 'پایگاه داده')], max_length=100, verbose_name='خدمات')),
                ('type', models.CharField(choices=[('1', 'برنزی'), ('2', 'نقره ایی'), ('3', 'طلایی')], max_length=1, verbose_name='نوع پکیج')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت به تومان')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن ها',
            },
        ),
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ نهایی')),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packege_requests', to='payments.package', verbose_name='پلن')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_packege_requests', to='accounts.student', verbose_name='داوطلب')),
            ],
            options={
                'verbose_name': 'درخواست پلن',
                'verbose_name_plural': 'درخواست های پلن',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('authority', models.CharField(max_length=100, unique=True)),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('gateway', models.CharField(default='zarinpal', max_length=50)),
                ('status', models.CharField(choices=[('INIT', 'ایجاد شده'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('CANCELED', 'لغو شده')], default='INIT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payments.packagerequest')),
            ],
            options={
                'verbose_name': 'فاکتور پرداخت',
                'verbose_name_plural': 'فاکتور های پرداخت',
            },
        ),
        migrations.CreateModel(
            name='ServiceToStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=1, verbose_name='کد خدمت')),
                ('is_used', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_to_services', to='accounts.student', verbose_name='داوطلب')),
            ],
            options={
                'verbose_name': 'خدمت به داوطلب',
                'verbose_name_plural': 'خدمت ها به داوطلبان',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_consultations', to='accounts.consultantschedule', verbose_name='برنامه حضور')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='payments.servicetostudent', verbose_name='خدمت خریداری شده')),
            ],
            options={
                'verbose_name': 'جلسه مشاوره',
                'verbose_name_plural': 'جلسات مشاوره',
            },
        ),
    ]
