# Generated by Django 6.0.5 on 2026-07-03 17:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='service',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'جلسه فردی با دکتر نایب زاده'), ('2', 'جلسه فردی با مشاور'), ('3', 'تحلیل شخصیت'), ('4', 'تعیین شانس قبولی'), ('5', 'پایگاه داده')], max_length=100, verbose_name='خدمات'),
        ),
    ]
