# Generated by Django 6.0.5 on 2026-07-26 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد')),
                ('type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=10, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
                ('max_discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف تخفیف')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 یعنی نامحدود')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('minimum_amount', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('packages', models.ManyToManyField(blank=True, to='payments.package', verbose_name='پلن\u200cهای مجاز')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.discountcode'),
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.discountcode')),
                ('package_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.packagerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discount', 'user', 'package_request')},
            },
        ),
    ]
