# Generated by Django 6.0.5 on 2026-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_packagerequest_discount_amount_discountcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='apply_to_all_packages',
            field=models.BooleanField(default=False, verbose_name='برای همه پلن\u200cها'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='apply_to_all_users',
            field=models.BooleanField(default=False, verbose_name='برای همه کاربران'),
        ),
    ]
