# Generated by Django 6.0.5 on 2026-07-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_discountcode_apply_to_all_packages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kiani_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('zarinpal', 'زرین پال'), ('snapppay', 'اسنپ پی'), ('digipay', 'دیجی پی')], default='zarinpal', max_length=20),
        ),
    ]
