# Generated by Django 6.0.5 on 2026-07-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_kiani_id_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_before_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت قبل از تخفیف (اختیاری)'),
        ),
    ]
