# Generated by Django 6.0.5 on 2026-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_package_price_before_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='پکیج آتروپین', max_length=200, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
