# Generated by Django 6.0.5 on 2026-07-31 21:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
    ]
