# Generated by Django 6.0.5 on 2026-08-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_package_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-id'], 'verbose_name': 'جلسه مشاوره', 'verbose_name_plural': 'جلسات مشاوره'},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['-id'], 'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='discountusage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-id'], 'verbose_name': 'پلن', 'verbose_name_plural': 'پلن ها'},
        ),
        migrations.AlterModelOptions(
            name='packagerequest',
            options={'ordering': ['-id'], 'verbose_name': 'درخواست پلن', 'verbose_name_plural': 'درخواست های پلن'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'فاکتور پرداخت', 'verbose_name_plural': 'فاکتور های پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='servicetostudent',
            options={'ordering': ['-id'], 'verbose_name': 'خدمت به داوطلب', 'verbose_name_plural': 'خدمت ها به داوطلبان'},
        ),
    ]
