# Generated by Django 6.0.5 on 2026-08-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_consultant_show_schedules'),
        ('payments', '0008_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('wallet', 'کیف پول'), ('zarinpal', 'زرین پال'), ('snapppay', 'اسنپ پی'), ('digipay', 'دیجی پی')], default='zarinpal', max_length=20),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.student')),
            ],
        ),
    ]
