# Generated by Django 6.0.5 on 2026-08-06 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_consultant_show_schedules'),
        ('payments', '0009_payment_gateway_amount_payment_wallet_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-id'], 'verbose_name': 'کیف پول داوطلب', 'verbose_name_plural': 'کیف های پول داوطلب'},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.student', verbose_name='داوطلب'),
        ),
    ]
