# Generated by Django 6.0.5 on 2026-08-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_wallet_options_alter_wallet_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-id'], 'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف های پول'},
        ),
    ]
