# Generated by Django 6.0.5 on 2026-08-06 13:25

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='service',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'جلسه فردی با دکتر نایب زاده'), ('2', 'جلسه فردی با دکتر جهان\u200cتیغ'), ('3', 'تحلیل شخصیت'), ('4', 'تعیین شانس قبولی'), ('5', 'پایگاه داده')], max_length=100, verbose_name='خدمات'),
        ),
    ]
