# Generated by Django 6.0.5 on 2026-08-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_package_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='نمایش عمومی'),
        ),
    ]
