# Generated by Django 6.0.5 on 2026-08-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_package_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=30, verbose_name='کد'),
        ),
    ]
