# Generated by Django 6.0.5 on 2026-06-26 07:30

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('rank', models.CharField(max_length=255, verbose_name='مقام یا رتبه')),
                ('cover', models.ImageField(upload_to='achievements/', verbose_name='کاور')),
            ],
            options={
                'verbose_name': 'افتخار',
                'verbose_name_plural': 'افتخارات',
            },
        ),
        migrations.CreateModel(
            name='ChoiceIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='introductions/counseling/', verbose_name='ویدئو معرفی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
            ],
            options={
                'verbose_name': 'معرفی انتخاب رشته',
                'verbose_name_plural': 'معرفی های انتخاب رشته',
            },
        ),
        migrations.CreateModel(
            name='CounselingIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='introductions/counseling/', verbose_name='ویدئو معرفی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
            ],
            options={
                'verbose_name': 'معرفی مشاوره',
                'verbose_name_plural': 'معرفی های مشاوره',
            },
        ),
        migrations.CreateModel(
            name='EstimationIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='introductions/counseling/', verbose_name='ویدئو معرفی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
            ],
            options={
                'verbose_name': 'معرفی تخمین قبولی',
                'verbose_name_plural': 'معرفی های تخمین قبولی',
            },
        ),
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان لایو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover', models.ImageField(upload_to='live_events/', verbose_name='کاور')),
                ('start_datetime', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_datetime', models.DateTimeField(verbose_name='زمان پایان')),
                ('stream_url', models.URLField(verbose_name='لینک پخش')),
                ('is_public', models.BooleanField(default=True, verbose_name='نمایش عمومی')),
            ],
            options={
                'verbose_name': 'لایو',
                'verbose_name_plural': 'لایوها',
            },
        ),
        migrations.CreateModel(
            name='LiveIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='introductions/counseling/', verbose_name='ویدئو معرفی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
            ],
            options={
                'verbose_name': 'معرفی وبینار',
                'verbose_name_plural': 'معرفی های وبینار',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='news/', verbose_name='تصویر')),
                ('content', models.TextField(verbose_name='متن')),
                ('is_public', models.BooleanField(default=True, verbose_name='نمایش عمومی')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبرها',
            },
        ),
        migrations.CreateModel(
            name='PlansIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='introductions/counseling/', verbose_name='ویدئو معرفی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
            ],
            options={
                'verbose_name': 'معرفی خدمت',
                'verbose_name_plural': 'معرفی های خدمت',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('cover', models.ImageField(upload_to='stories/cover/', verbose_name='کاور')),
                ('content', models.FileField(upload_to='stories/content/', verbose_name='محتوا استوری')),
            ],
            options={
                'verbose_name': 'استوری',
                'verbose_name_plural': 'استوری ها',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نظرسنجی')),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': 'نظرسنجی ها',
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='گزینه')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.survey', verbose_name='نظرسنجی')),
            ],
            options={
                'verbose_name': 'گزینه نظرسنجی',
                'verbose_name_plural': 'گزینه های نظرسنجی',
            },
        ),
    ]
