# Generated by Django 6.0.5 on 2026-07-03 17:08

import django_ckeditor_5.fields
import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='introductions/about_us/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
            ],
            options={
                'verbose_name': 'معرفی ما',
                'verbose_name_plural': 'معرفی های ما',
            },
        ),
        migrations.AlterField(
            model_name='choiceintroduction',
            name='video',
            field=models.FileField(upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='counselingintroduction',
            name='video',
            field=models.FileField(upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='estimationintroduction',
            name='video',
            field=models.FileField(upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='liveintroduction',
            name='video',
            field=models.FileField(upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='plansintroduction',
            name='video',
            field=models.FileField(upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
    ]
