# Generated by Django 6.0.5 on 2026-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutusintroduction_alter_choiceintroduction_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='posters/', verbose_name='پوستر')),
                ('title', models.CharField(verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'پوستر',
                'verbose_name_plural': 'پوستر ها',
            },
        ),
    ]
