# Generated by Django 6.0.5 on 2026-07-06 19:14

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='title',
        ),
        migrations.AddField(
            model_name='poster',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'جلسه فردی با دکتر نایب زاده'), ('2', 'جلسه فردی با مشاور'), ('3', 'تحلیل شخصیت'), ('4', 'تعیین شانس قبولی'), ('5', 'پایگاه داده')], default='1', max_length=100, verbose_name='نمایش در صفحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='stream_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک پخش'),
        ),
    ]
