# Generated by Django 6.0.5 on 2026-07-07 14:09

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_poster_title_poster_show_in_poster_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین')], default='main', max_length=100, verbose_name='نمایش در صفحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین')], default='main', max_length=100, verbose_name='نمایش در صفحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poster',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین')], max_length=100, verbose_name='نمایش در صفحات'),
        ),
    ]
