# Generated by Django 6.0.5 on 2026-07-12 13:21

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_comment_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveevent',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین'), ('choice', 'صفحه جلسات فردی انتخاب رشته')], max_length=100, verbose_name='نمایش در صفحات'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین'), ('choice', 'صفحه جلسات فردی انتخاب رشته')], max_length=100, verbose_name='نمایش در صفحات'),
        ),
        migrations.AlterField(
            model_name='story',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین'), ('choice', 'صفحه جلسات فردی انتخاب رشته')], max_length=100, verbose_name='نمایش در صفحات'),
        ),
    ]
