# Generated by Django 6.0.5 on 2026-07-16 07:48

import django_ckeditor_5.fields
import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_liveevent_show_in_alter_poster_show_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
            ],
            options={
                'verbose_name': 'معرفی پایگاه داده',
                'verbose_name_plural': 'معرفی های پایگاه داده',
            },
        ),
    ]
