# Generated by Django 6.0.5 on 2026-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_dataintroduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='media_content/', verbose_name='محتوا')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media_cover/', verbose_name='کاور')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مدیا',
                'verbose_name_plural': 'مدیا ها',
            },
        ),
        migrations.CreateModel(
            name='RankBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='رتبه')),
                ('quota', models.CharField(choices=[('1', 'آزاد'), ('2', 'محروم'), ('3', 'ایثارگران ۵٪'), ('4', 'ایثارگران ۲۵٪'), ('5', 'سایر')], max_length=1, verbose_name='سهمیه')),
                ('field', models.CharField(max_length=200, verbose_name='رشته قبولی')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'رتبه قبولی',
                'verbose_name_plural': 'رتبه قبولی ها',
            },
        ),
    ]
