# Generated by Django 6.0.5 on 2026-07-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_media_rankbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('video', 'ویدئوهای معرفی اختصاصی رشته ها'), ('voice', 'ویس های بررسی رشته شهرها'), ('else_video', 'سایر ویدئوها'), ('else_voice', 'سایر ویس ها')], default='', max_length=100, verbose_name='نوع مدیا'),
            preserve_default=False,
        ),
    ]
