# Generated by Django 6.0.5 on 2026-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='رایگان'),
        ),
    ]
