# Generated by Django 6.0.5 on 2026-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_media_is_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='rules/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'قانون',
                'verbose_name_plural': 'قوانین',
            },
        ),
    ]
