# Generated by Django 6.0.5 on 2026-07-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankbank',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rules/', verbose_name='تصویر'),
        ),
    ]
