# Generated by Django 6.0.5 on 2026-07-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_rankbank_description_alter_rule_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('1', 'ادمین'), ('2', 'داوطلب')], max_length=1, verbose_name='ارسال کننده')),
                ('text', models.CharField(max_length=600, verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام ثابت',
                'verbose_name_plural': 'پیام های ثابت',
            },
        ),
    ]
