# Generated by Django 6.0.5 on 2026-07-21 19:22

import multiselectfield.db.fields
import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_staticmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusintroduction',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='introductions/about_us/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='choiceintroduction',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='counselingintroduction',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='dataintroduction',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='estimationintroduction',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین'), ('archives', 'صفحه آرشیو لایو های سال های قبل')], max_length=100, verbose_name='نمایش در صفحات'),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='stream_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک پخش'),
        ),
        migrations.AlterField(
            model_name='liveintroduction',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='plansintroduction',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='introductions/counseling/', validators=[pages.validators.validate_video], verbose_name='ویدئو معرفی'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین'), ('choice', 'صفحه جلسات فردی انتخاب رشته'), ('DataIntroduction', 'صفحه معرفی پایگاه داده'), ('AboutUsIntroduction', 'صفحه درباره\u200cما')], max_length=100, verbose_name='نمایش در صفحات'),
        ),
        migrations.AlterField(
            model_name='story',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین')], max_length=100, verbose_name='نمایش در صفحات'),
        ),
    ]
