# Generated by Django 6.0.5 on 2026-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_aboutusintroduction_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='aparat_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک آپارات'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ویدئو'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='year',
            field=models.CharField(default='1405', max_length=4, verbose_name='سال شمسی برگزاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(default='مشاوره', max_length=200, verbose_name='دسته بندی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='year',
            field=models.CharField(default='1405', max_length=4, verbose_name='سال شمسی برگزاری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع'),
        ),
    ]
