# Generated by Django 6.0.5 on 2026-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_liveevent_aparat_url_liveevent_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='category',
            field=models.CharField(default='آموزشی', max_length=200, verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
