# Generated by Django 6.0.5 on 2026-07-23 07:32

import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_liveevent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lives/', validators=[pages.validators.validate_video], verbose_name='ویدئو'),
        ),
    ]
