# Generated by Django 6.0.5 on 2026-07-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_liveevent_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankbank',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='رایگان'),
        ),
    ]
