# Generated by Django 6.0.5 on 2026-07-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_rankbank_is_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200, verbose_name='رشته قبولی')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
            ],
            options={
                'verbose_name': 'دسته بندی رشته',
                'verbose_name_plural': 'دسته بندی رشته ها',
            },
        ),
        migrations.RemoveField(
            model_name='rankbank',
            name='is_free',
        ),
        migrations.AlterField(
            model_name='rankbank',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank_field_bank', to='pages.rankfield', verbose_name='رشته قبولی'),
        ),
    ]
