# Generated by Django 6.0.5 on 2026-07-29 19:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_rankfield_remove_rankbank_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveevent',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات'),
        ),
    ]
