# Generated by Django 6.0.5 on 2026-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_liveevent_description_alter_media_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmessage',
            name='sender',
            field=models.CharField(choices=[('1', 'جواب'), ('2', 'سوال')], max_length=1, verbose_name='ارسال کننده'),
        ),
    ]
