# Generated by Django 6.0.5 on 2026-07-31 21:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_staticmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusintroduction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='choiceintroduction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='counselingintroduction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='dataintroduction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='estimationintroduction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='liveintroduction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='plansintroduction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='معرفی و توضیحات'),
        ),
    ]
