# Generated by Django 6.0.5 on 2026-08-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_aboutusintroduction_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusintroduction',
            options={'ordering': ['-id'], 'verbose_name': 'معرفی ما', 'verbose_name_plural': 'معرفی های ما'},
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-id'], 'verbose_name': 'افتخار', 'verbose_name_plural': 'افتخارات'},
        ),
        migrations.AlterModelOptions(
            name='choiceintroduction',
            options={'ordering': ['-id'], 'verbose_name': 'معرفی انتخاب رشته', 'verbose_name_plural': 'معرفی های انتخاب رشته'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='counselingintroduction',
            options={'ordering': ['-id'], 'verbose_name': 'معرفی مشاوره', 'verbose_name_plural': 'معرفی های مشاوره'},
        ),
        migrations.AlterModelOptions(
            name='dataintroduction',
            options={'ordering': ['-id'], 'verbose_name': 'معرفی پایگاه داده', 'verbose_name_plural': 'معرفی های پایگاه داده'},
        ),
        migrations.AlterModelOptions(
            name='estimationintroduction',
            options={'ordering': ['-id'], 'verbose_name': 'معرفی تخمین قبولی', 'verbose_name_plural': 'معرفی های تخمین قبولی'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-id'], 'verbose_name': 'پرسش و پاسخ', 'verbose_name_plural': 'پرسش و پاسخ ها'},
        ),
        migrations.AlterModelOptions(
            name='liveevent',
            options={'ordering': ['-id'], 'verbose_name': 'لایو', 'verbose_name_plural': 'لایوها'},
        ),
        migrations.AlterModelOptions(
            name='liveintroduction',
            options={'ordering': ['-id'], 'verbose_name': 'معرفی وبینار', 'verbose_name_plural': 'معرفی های وبینار'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-id'], 'verbose_name': 'مدیا', 'verbose_name_plural': 'مدیا ها'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'خبر', 'verbose_name_plural': 'خبرها'},
        ),
        migrations.AlterModelOptions(
            name='plansintroduction',
            options={'ordering': ['-id'], 'verbose_name': 'معرفی خدمت', 'verbose_name_plural': 'معرفی های خدمت'},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'ordering': ['-id'], 'verbose_name': 'پوستر', 'verbose_name_plural': 'پوستر ها'},
        ),
        migrations.AlterModelOptions(
            name='rankbank',
            options={'ordering': ['-id'], 'verbose_name': 'رتبه قبولی', 'verbose_name_plural': 'رتبه قبولی ها'},
        ),
        migrations.AlterModelOptions(
            name='rankfield',
            options={'ordering': ['-id'], 'verbose_name': 'دسته بندی رشته', 'verbose_name_plural': 'دسته بندی رشته ها'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['-id'], 'verbose_name': 'قانون', 'verbose_name_plural': 'قوانین'},
        ),
        migrations.AlterModelOptions(
            name='staticmessage',
            options={'ordering': ['id'], 'verbose_name': 'پیام ثابت', 'verbose_name_plural': 'پیام های ثابت'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-id'], 'verbose_name': 'استوری', 'verbose_name_plural': 'استوری ها'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-id'], 'verbose_name': 'نظرسنجی', 'verbose_name_plural': 'نظرسنجی ها'},
        ),
        migrations.AlterModelOptions(
            name='surveyoption',
            options={'ordering': ['-id'], 'verbose_name': 'گزینه نظرسنجی', 'verbose_name_plural': 'گزینه های نظرسنجی'},
        ),
    ]
