# Generated by Django 6.0.5 on 2026-08-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_aboutusintroduction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-is_free', '-id'], 'verbose_name': 'مدیا', 'verbose_name_plural': 'مدیا ها'},
        ),
    ]
