# Generated by Django 6.0.5 on 2026-08-09 20:02

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_media_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankbank',
            options={'ordering': ['rank'], 'verbose_name': 'رتبه قبولی', 'verbose_name_plural': 'رتبه قبولی ها'},
        ),
        migrations.AlterField(
            model_name='poster',
            name='show_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'صفحه خانه'), ('compass', 'صفحه قطب نمای آتروپین'), ('choice', 'صفحه جلسات فردی انتخاب رشته'), ('lives', 'لایو های تخصصی انتخاب رشته'), ('DataIntroduction', 'صفحه معرفی پایگاه داده'), ('AboutUsIntroduction', 'صفحه درباره\u200cما')], max_length=100, verbose_name='نمایش در صفحات'),
        ),
    ]
