# Generated by Django 6.0.5 on 2026-08-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_rankbank_options_alter_poster_show_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='درحال برگزاری'),
        ),
    ]
