# Generated by Django 6.0.5 on 2026-08-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_liveevent_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='staticmessage',
            name='text',
            field=models.TextField(verbose_name='متن پیام'),
        ),
    ]
