# Generated by Django 6.0.5 on 2026-06-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_consultant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subgroup', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'رشته',
                'verbose_name_plural': 'رشته\u200cها',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'دانشگاه',
                'verbose_name_plural': 'دانشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='UniversityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quota', models.CharField(choices=[('free', 'آزاد'), ('5', '۵ درصد'), ('25', '۲۵ درصد'), ('city1', 'محروم ۱'), ('city2', 'محروم ۲')], max_length=20)),
                ('accepted_rank', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField()),
                ('is_day', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.university')),
            ],
            options={
                'verbose_name': 'قبولی سال گذشته',
                'verbose_name_plural': 'قبولی\u200cهای سال\u200cهای گذشته',
            },
        ),
    ]
