# Generated by Django 6.0.5 on 2026-06-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_major_university_universityresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityresult',
            name='major',
        ),
        migrations.RemoveField(
            model_name='universityresult',
            name='university',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='UniversityResult',
        ),
    ]
