# Generated by Django 6.0.5 on 2026-07-01 13:57

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_universityresult_major_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(verbose_name='معرفی و توضیحات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_consultant', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشاور',
                'verbose_name_plural': 'مشاورین',
            },
        ),
        migrations.CreateModel(
            name='ConsultantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consultant', verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'برنامه حضور مشاور',
                'verbose_name_plural': 'برنامه های حضور مشاور',
            },
        ),
    ]
