# Generated by Django 6.0.5 on 2026-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consultant_consultantschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantschedule',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='رزرو شده؟'),
        ),
    ]
