# Generated by Django 6.0.5 on 2026-08-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_consultantschedule_is_reserved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ab',
            options={'ordering': ['-id'], 'verbose_name': 'فرم اطلاعات A و B', 'verbose_name_plural': 'فرم های اطلاعات A و B'},
        ),
        migrations.AlterModelOptions(
            name='consultantschedule',
            options={'ordering': ['-id'], 'verbose_name': 'برنامه حضور مشاور', 'verbose_name_plural': 'برنامه های حضور مشاور'},
        ),
        migrations.AlterModelOptions(
            name='personality60',
            options={'ordering': ['-id'], 'verbose_name': 'فرم تحلیل شخصیت 60 سوالی', 'verbose_name_plural': 'فرم های تحلیل شخصیت 60 سوالی'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['-id'], 'verbose_name': 'فرم اطلاعات رتبه سهمیه', 'verbose_name_plural': 'فرم های اطلاعات رتبه سهمیه'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id'], 'verbose_name': 'داوطلب', 'verbose_name_plural': 'داوطلبان'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
