# Generated by Django 6.0.5 on 2026-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_ab_options_alter_consultantschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='show_schedules',
            field=models.BooleanField(default=True, verbose_name='نمایش نوبت های مشاوره'),
        ),
    ]
