# Generated by Django 6.0.5 on 2026-08-06 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_consultant_show_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('result', models.CharField(blank=True, max_length=2, verbose_name='نتیجه ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('students', models.ManyToManyField(related_name='received_sms', to='accounts.student', verbose_name='گیرندگان')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ['-id'],
            },
        ),
    ]
