# Generated by Django 6.0.5 on 2026-08-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('telegram_id', models.CharField(max_length=100, verbose_name='آیدی تلگرام')),
                ('age', models.PositiveSmallIntegerField(verbose_name='سن')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل زندگی')),
                ('university', models.CharField(max_length=200, verbose_name='دانشگاه محل تحصیل دوره عمومی')),
                ('marital_status', models.CharField(max_length=200, verbose_name='وضعیت تأهل و فرزند')),
                ('spouse_job', models.CharField(blank=True, max_length=200, verbose_name='شغل همسر')),
                ('employment_status', models.CharField(blank=True, max_length=200, verbose_name='وضعیت استخدام')),
                ('service_status', models.TextField(blank=True, verbose_name='وضعیت گذراندن طرح یا سربازی')),
                ('other_description', models.TextField(blank=True, verbose_name='سایر موارد مرتبط')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_form_1', to='accounts.student', verbose_name='داوطلب')),
            ],
            options={
                'verbose_name': 'فرم شماره 1',
                'verbose_name_plural': 'فرم های شماره 1',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentForm2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='نمره دستیاری ۴۰۵')),
                ('assistant_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه دستیاری ۴۰۵')),
                ('subgroup1_rank', models.PositiveIntegerField(verbose_name='رتبه زیرگروه یک')),
                ('subgroup2_rank', models.PositiveIntegerField(verbose_name='رتبه زیرگروه دو')),
                ('subgroup3_rank', models.PositiveIntegerField(verbose_name='رتبه زیرگروه سه')),
                ('subgroup4_rank', models.PositiveIntegerField(verbose_name='رتبه زیرگروه چهار')),
                ('subgroup5_rank', models.PositiveIntegerField(verbose_name='رتبه زیرگروه پنج')),
                ('quota', models.CharField(blank=True, max_length=200, verbose_name='نوع سهمیه')),
                ('quota_25_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه سهمیه ایثارگران ۲۵٪')),
                ('quota_5_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه سهمیه ایثارگران ۵٪')),
                ('deprived_area1_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه سهمیه محروم استان ۱')),
                ('deprived_area2_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه سهمیه محروم استان ۲')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_form_2', to='accounts.student', verbose_name='داوطلب')),
            ],
            options={
                'verbose_name': 'فرم شماره 2',
                'verbose_name_plural': 'فرم های شماره 2',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentForm3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_specialties', models.TextField(verbose_name='رشته\u200cهای مورد علاقه')),
                ('city_priority', models.PositiveSmallIntegerField(verbose_name='اولویت انتخاب شهر')),
                ('preferred_cities', models.TextField(verbose_name='شهرهای مورد نظر')),
                ('main_challenge', models.TextField(verbose_name='چالش اصلی انتخاب رشته')),
                ('career_motivation', models.TextField(verbose_name='مهم\u200cترین انگیزه شغلی')),
                ('reason_for_medicine', models.TextField(verbose_name='علت انتخاب پزشکی')),
                ('risk_taking', models.PositiveSmallIntegerField(verbose_name='ریسک\u200cپذیری')),
                ('personality_type', models.CharField(max_length=100, verbose_name='درون\u200cگرا یا برون\u200cگرا')),
                ('leadership', models.PositiveSmallIntegerField(verbose_name='توانایی لیدر بودن')),
                ('empathy', models.PositiveSmallIntegerField(verbose_name='میزان همدلی')),
                ('patient_interest', models.PositiveSmallIntegerField(verbose_name='علاقه به مریض دیدن')),
                ('interested_in_surgery', models.CharField(max_length=10, verbose_name='علاقه\u200cمند به جراح شدن')),
                ('income_expectation', models.CharField(max_length=50, verbose_name='درآمد مورد نظر')),
                ('procedure_interest', models.CharField(max_length=100, verbose_name='تمایل به پروسیجر یا طبابت')),
                ('night_shift_priority', models.CharField(max_length=100, verbose_name='اولویت نداشتن کشیک')),
                ('hospital_environment_annoying', models.CharField(max_length=100, verbose_name='آزاردهنده بودن حضور طولانی در بیمارستان')),
                ('preferred_workplace', models.CharField(max_length=100, verbose_name='محیط کاری مورد علاقه')),
                ('free_time_importance', models.PositiveSmallIntegerField(verbose_name='اهمیت داشتن تایم آزاد')),
                ('strong_internship_departments', models.TextField(verbose_name='بخش\u200cهای قوی دوران اینترنی')),
                ('internship_shifts', models.CharField(max_length=200, verbose_name='وضعیت کشیک\u200cهای اینترنی')),
                ('decision_making', models.PositiveSmallIntegerField(verbose_name='قدرت تصمیم\u200cگیری در شرایط بحرانی')),
                ('prefer_variety', models.CharField(max_length=100, verbose_name='ترجیح تنوع یا یکنواختی')),
                ('hand_or_thinking', models.CharField(max_length=100, verbose_name='ترجیح کار با دست یا فکر')),
                ('world_impact', models.CharField(max_length=100, verbose_name='تمایل به تأثیرگذاری در جهان')),
                ('team_or_individual', models.CharField(max_length=100, verbose_name='علاقه به کار گروهی یا فردی')),
                ('work_independence', models.CharField(max_length=100, verbose_name='اهمیت استقلال کاری')),
                ('affected_by_critical_patient', models.CharField(max_length=100, verbose_name='تأثیرپذیری از بیمار بدحال')),
                ('communication_interest', models.PositiveSmallIntegerField(verbose_name='علاقه به ارتباط کلامی با بیمار')),
                ('research_interest', models.PositiveSmallIntegerField(verbose_name='علاقه به پژوهش')),
                ('opposite_gender_exam', models.CharField(max_length=100, verbose_name='سخت بودن معاینه بیمار غیرهم\u200cجنس')),
                ('additional_notes', models.TextField(blank=True, verbose_name='توضیحات تکمیلی')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_form_3', to='accounts.student', verbose_name='داوطلب')),
            ],
            options={
                'verbose_name': 'فرم شماره 3',
                'verbose_name_plural': 'فرم های شماره 3',
                'ordering': ['-id'],
            },
        ),
    ]
