# Generated by Django 6.0.5 on 2026-08-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentform1_studentform2_studentform3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform1',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='سن *'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر محل زندگی *'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی *'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='marital_status',
            field=models.CharField(max_length=200, verbose_name='وضعیت تأهل و فرزند *'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='شماره تماس *'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='telegram_id',
            field=models.CharField(max_length=100, verbose_name='آیدی تلگرام *'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='university',
            field=models.CharField(max_length=200, verbose_name='دانشگاه محل تحصیل دوره عمومی *'),
        ),
    ]
