# Generated by Django 6.0.5 on 2026-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_studentform1_age_alter_studentform1_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform1',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='* سن'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='city',
            field=models.CharField(max_length=100, verbose_name='* شهر محل زندگی'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='* نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='marital_status',
            field=models.CharField(max_length=200, verbose_name='* وضعیت تأهل و فرزند'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='* شماره تماس'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='telegram_id',
            field=models.CharField(max_length=100, verbose_name='* آیدی تلگرام'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='university',
            field=models.CharField(max_length=200, verbose_name='* دانشگاه محل تحصیل دوره عمومی'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='assistant_score',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='* نمره دستیاری ۴۰۵'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup1_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه زیرگروه یک'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup2_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه زیرگروه دو'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup3_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه زیرگروه سه'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup4_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه زیرگروه چهار'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup5_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه زیرگروه پنج'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='* توضیحات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='affected_by_critical_patient',
            field=models.CharField(max_length=100, verbose_name='* تأثیرپذیری از بیمار بدحال'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='career_motivation',
            field=models.TextField(verbose_name='* مهم\u200cترین انگیزه شغلی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='city_priority',
            field=models.PositiveSmallIntegerField(verbose_name='* اولویت انتخاب شهر'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='communication_interest',
            field=models.PositiveSmallIntegerField(verbose_name='* علاقه به ارتباط کلامی با بیمار'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='decision_making',
            field=models.PositiveSmallIntegerField(verbose_name='* قدرت تصمیم\u200cگیری در شرایط بحرانی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='empathy',
            field=models.PositiveSmallIntegerField(verbose_name='* میزان همدلی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='favorite_specialties',
            field=models.TextField(verbose_name='* رشته\u200cهای مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='free_time_importance',
            field=models.PositiveSmallIntegerField(verbose_name='* اهمیت داشتن تایم آزاد'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='hand_or_thinking',
            field=models.CharField(max_length=100, verbose_name='* ترجیح کار با دست یا فکر'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='hospital_environment_annoying',
            field=models.CharField(max_length=100, verbose_name='* آزاردهنده بودن حضور طولانی در بیمارستان'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='income_expectation',
            field=models.CharField(max_length=50, verbose_name='* درآمد مورد نظر'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='interested_in_surgery',
            field=models.CharField(max_length=10, verbose_name='* علاقه\u200cمند به جراح شدن'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='internship_shifts',
            field=models.CharField(max_length=200, verbose_name='* وضعیت کشیک\u200cهای اینترنی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='leadership',
            field=models.PositiveSmallIntegerField(verbose_name='* توانایی لیدر بودن'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='main_challenge',
            field=models.TextField(verbose_name='* چالش اصلی انتخاب رشته'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='night_shift_priority',
            field=models.CharField(max_length=100, verbose_name='* اولویت نداشتن کشیک'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='opposite_gender_exam',
            field=models.CharField(max_length=100, verbose_name='* سخت بودن معاینه بیمار غیرهم\u200cجنس'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='patient_interest',
            field=models.PositiveSmallIntegerField(verbose_name='* علاقه به مریض دیدن'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='personality_type',
            field=models.CharField(max_length=100, verbose_name='* درون\u200cگرا یا برون\u200cگرا'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='prefer_variety',
            field=models.CharField(max_length=100, verbose_name='* ترجیح تنوع یا یکنواختی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='preferred_cities',
            field=models.TextField(verbose_name='* شهرهای مورد نظر'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='preferred_workplace',
            field=models.CharField(max_length=100, verbose_name='* محیط کاری مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='procedure_interest',
            field=models.CharField(max_length=100, verbose_name='* تمایل به پروسیجر یا طبابت'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='reason_for_medicine',
            field=models.TextField(verbose_name='* علت انتخاب پزشکی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='research_interest',
            field=models.PositiveSmallIntegerField(verbose_name='* علاقه به پژوهش'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='risk_taking',
            field=models.PositiveSmallIntegerField(verbose_name='* ریسک\u200cپذیری'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='strong_internship_departments',
            field=models.TextField(verbose_name='* بخش\u200cهای قوی دوران اینترنی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='team_or_individual',
            field=models.CharField(max_length=100, verbose_name='* علاقه به کار گروهی یا فردی'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='work_independence',
            field=models.CharField(max_length=100, verbose_name='* اهمیت استقلال کاری'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='world_impact',
            field=models.CharField(max_length=100, verbose_name='* تمایل به تأثیرگذاری در جهان'),
        ),
    ]
