# Generated by Django 6.0.5 on 2026-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_studentform1_age_alter_studentform1_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_limited',
            field=models.BooleanField(default=False, verbose_name='دسترسی محدود (برای مدیرکل)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدیرکل'), ('supervisor', 'ناظر'), ('consultant', 'مشاور'), ('student', 'داوطلب')], max_length=30, verbose_name='نقش'),
        ),
    ]
