# Generated by Django 6.0.5 on 2026-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_is_limited_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform1',
            name='city',
            field=models.CharField(max_length=100, verbose_name='* شهر فعلی محل زندگی'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='employment_status',
            field=models.CharField(blank=True, max_length=200, verbose_name='آیا استخدام جایی هستید؟'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='mobile',
            field=models.CharField(help_text='همان شماره که برای ادمین آتروپین ارسال کردید یا با آن وارد سامانه شدید', max_length=11, verbose_name='* شماره تماس'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='other_description',
            field=models.TextField(blank=True, verbose_name='سایر موارد مرتبط را ذکر کنید'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='service_status',
            field=models.TextField(blank=True, help_text='ذکر محل خدمت: اورژانس، بهداشت، درمانگاه\u200cهای نیروهای مسلح یا سایر', verbose_name='وضعیت گذراندن دوره طرح یا سربازی'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='telegram_id',
            field=models.CharField(help_text='اگر آیدی ندارید لطفا بسازید چون برای پیدا کردن شما در بین انبوده پیام های دریافتی، ضرورت دارد', max_length=100, verbose_name='* آیدی تلگرام'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='assistant_score',
            field=models.DecimalField(decimal_places=2, help_text='با کلید نهایی سنجش', max_digits=6, verbose_name='* نمره دستیاری ۴۰۵'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='deprived_area1_rank',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت وجود', null=True, verbose_name='سهمیه محروم استان ۱'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='deprived_area2_rank',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت وجود', null=True, verbose_name='سهمیه محروم استان ۲'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='quota',
            field=models.CharField(blank=True, help_text='نوع سهمیه - در صورت وجود', max_length=200, verbose_name='وضعیت سهمیه'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='quota_25_rank',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت وجود', null=True, verbose_name='رتبه سهمیه ایثارگران ۲۵٪'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='quota_5_rank',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت وجود', null=True, verbose_name='سهمیه ایثارگران ۵٪'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup1_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه در زیر گروه یک'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup2_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه در زیر گروه دو'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup3_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه در زیر گروه سه'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup4_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه در زیر گروه چهار'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='subgroup5_rank',
            field=models.PositiveIntegerField(verbose_name='* رتبه در زیر گروه پنج'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='هر نکته\u200cای که با توجه به شرایط\u200cتان نیاز است مشاور در جریان باشد، ذکر کنید'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='affected_by_critical_patient',
            field=models.CharField(max_length=100, verbose_name='* آیا در برخورد با بیمار بدحال بیش از معمول تحت تأثیر قرار می\u200cگیرید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='career_motivation',
            field=models.TextField(help_text='پول، پرستیژ، نجات افراد و...', verbose_name='* مهم\u200cترین انگیزه شغلی فعلی شما'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='city_priority',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* انتخاب شهر برای شما چقدر اولویت دارد؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='communication_interest',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* آیا به ارتباط کلامی با بیماران علاقه\u200cمندید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='decision_making',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* قدرت تصمیم\u200cگیری شما در شرایط بحرانی؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='empathy',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* میزان همدلی شما با افراد و بیماران؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='favorite_specialties',
            field=models.TextField(verbose_name='* رشته\u200cهای مورد علاقه شما به ترتیب اولویت'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='free_time_importance',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* داشتن تایم آزاد چقدر برای شما اهمیت دارد؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='hand_or_thinking',
            field=models.CharField(max_length=100, verbose_name='* کار کردن با دست را ترجیح می\u200cدهید یا فکر کردن؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='hospital_environment_annoying',
            field=models.CharField(max_length=100, verbose_name='* آیا بودن طولانی\u200cمدت در محیط بیمارستان شما را آزار می\u200cدهد؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='income_expectation',
            field=models.CharField(help_text='بالا / متوسط', max_length=50, verbose_name='* درآمد مورد نظر'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='interested_in_surgery',
            field=models.CharField(help_text='بله/خیر', max_length=10, verbose_name='* علاقه\u200cمند به جراح شدن؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='internship_shifts',
            field=models.CharField(max_length=200, verbose_name='* کشیک\u200cهای دوران اینترنی را خودتان گذرانده\u200cاید یا به دیگران سپرده\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='leadership',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* توانایی لیدر بودن در جمع ؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='main_challenge',
            field=models.TextField(verbose_name='* چالش اصلی شما در بحث انتخاب رشته چیست؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='night_shift_priority',
            field=models.CharField(max_length=100, verbose_name='* کشیک نداشتن برای شما اولویت است؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='opposite_gender_exam',
            field=models.CharField(max_length=100, verbose_name='* آیا معاینه بیمار غیرهم\u200cجنس برای شما سخت است؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='patient_interest',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* علاقه\u200cمند به مریض دیدن؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='personality_type',
            field=models.CharField(max_length=100, verbose_name='* خود را فرد درون\u200cگرا می\u200cدانید یا برون\u200cگرا؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='prefer_variety',
            field=models.CharField(max_length=100, verbose_name='* تنوع را بر یکنواختی ترجیح می\u200cدهید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='preferred_cities',
            field=models.TextField(verbose_name='* گزینه\u200cهای اولویت\u200cبندی شده برای انتخاب شهر'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='preferred_workplace',
            field=models.CharField(max_length=100, verbose_name='* محیط بیمارستان و اورژانس را ترجیح می\u200cدهید یا مطب و درمانگاه؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='procedure_interest',
            field=models.CharField(max_length=100, verbose_name='* تمایل به پروسیجر در رشته دارید یا صرفاً طبابت بالینی؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='reason_for_medicine',
            field=models.TextField(verbose_name='* علت انتخاب پزشکی بعد از کنکور چه بود؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='research_interest',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* آیا به ریسرچ و پژوهش علاقه\u200cمندید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='risk_taking',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', verbose_name='* ریسک\u200cپذیر هستید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='strong_internship_departments',
            field=models.TextField(verbose_name='* در دوران اینترنی در کدام بخش\u200cها خود را توانمندتر می\u200cدانستید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='team_or_individual',
            field=models.CharField(max_length=100, verbose_name='* آیا به انجام کارهای گروهی علاقه\u200cمندید یا کارهای فردی؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='work_independence',
            field=models.CharField(max_length=100, verbose_name='* استقلال کاری برایتان اهمیت زیادی دارد؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='world_impact',
            field=models.CharField(max_length=100, verbose_name='* آیا دوست دارید فرد تأثیرگذاری در جهان باشید؟'),
        ),
    ]
