# Generated by Django 6.0.5 on 2026-08-16 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_studentform1_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform3',
            name='city_priority',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* انتخاب شهر برای شما چقدر اولویت دارد؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='communication_interest',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* آیا به ارتباط کلامی با بیماران علاقه\u200cمندید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='decision_making',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* قدرت تصمیم\u200cگیری شما در شرایط بحرانی؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='empathy',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* میزان همدلی شما با افراد و بیماران؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='free_time_importance',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* داشتن تایم آزاد چقدر برای شما اهمیت دارد؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='leadership',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* توانایی لیدر بودن در جمع ؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='patient_interest',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* علاقه\u200cمند به مریض دیدن؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='research_interest',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* آیا به ریسرچ و پژوهش علاقه\u200cمندید؟'),
        ),
        migrations.AlterField(
            model_name='studentform3',
            name='risk_taking',
            field=models.PositiveSmallIntegerField(help_text='۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='* ریسک\u200cپذیر هستید؟'),
        ),
    ]
