# Generated by Django 6.0.5 on 2026-08-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_studentform3_city_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantschedule',
            name='is_held',
            field=models.BooleanField(default=False, verbose_name='برگزار شده؟'),
        ),
    ]
