# Generated by Django 6.0.5 on 2026-09-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_consultantschedule_is_held'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform2',
            name='deprived_area1_name',
            field=models.CharField(blank=True, help_text='در صورت وجود', max_length=100, verbose_name='نام استان ۱'),
        ),
        migrations.AddField(
            model_name='studentform2',
            name='deprived_area2_name',
            field=models.CharField(blank=True, help_text='در صورت وجود', max_length=100, verbose_name='نام استان ۲'),
        ),
        migrations.AddField(
            model_name='studentform2',
            name='deprived_overall_rank',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت وجود', null=True, verbose_name='رتبه کل محروم'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='deprived_area1_rank',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت وجود', null=True, verbose_name='رتبه استان ۱'),
        ),
        migrations.AlterField(
            model_name='studentform2',
            name='deprived_area2_rank',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت وجود', null=True, verbose_name='رتبه استان ۲'),
        ),
    ]
