# Generated by Django 6.0.5 on 2026-06-19 10:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('service_type', models.CharField(choices=[('major_selection', 'انتخاب رشته'), ('academic_guidance', 'هدایت تحصیلی')], max_length=50, verbose_name='نوع مشاوره')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='consulting_videos/', verbose_name='ویدئو معرفی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='هزینه')),
            ],
            options={
                'verbose_name': 'خدمت مشاوره',
                'verbose_name_plural': 'خدمات مشاوره',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگوها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='تصویر')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='هزینه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='news/', verbose_name='تصویر')),
                ('content', models.TextField(verbose_name='متن')),
                ('is_public', models.BooleanField(default=True, verbose_name='نمایش عمومی')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبرها',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('cover', models.ImageField(upload_to='stories/', verbose_name='کاور')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'استوری',
                'verbose_name_plural': 'استوری ها',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نظرسنجی')),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': 'نظرسنجی ها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'مدیر کل'), ('supervisor', 'ناظر'), ('consultant', 'مشاور'), ('student', 'داوطلب')], max_length=30, verbose_name='نقش')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='شماره موبایل')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='تعلیق شده')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='دلیل تعلیق')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='حداکثر ظرفیت داوطلب')),
                ('bio', models.TextField(blank=True, verbose_name='معرفی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'پروفایل مشاور',
                'verbose_name_plural': 'پروفایل مشاوران',
            },
        ),
        migrations.CreateModel(
            name='ConsultantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='ظرفیت')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'برنامه حضور مشاور',
                'verbose_name_plural': 'برنامه های حضور مشاور',
            },
        ),
        migrations.CreateModel(
            name='ConsultingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(default=dict, verbose_name='اطلاعات فرم')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_requests', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.consultantschedule', verbose_name='زمان رزرو')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='داوطلب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.consultingservice', verbose_name='خدمت مشاوره')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست های مشاوره',
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.contentcategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته بندی محتوا',
                'verbose_name_plural': 'دسته بندی های محتوا',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content_type', models.CharField(choices=[('video', 'ویدئو'), ('audio', 'صوت'), ('pdf', 'فایل PDF'), ('article', 'مقاله')], max_length=20, verbose_name='نوع محتوا')),
                ('file', models.FileField(upload_to='contents/', verbose_name='فایل')),
                ('is_public', models.BooleanField(default=False, verbose_name='نمایش عمومی')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.contentcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتواها',
            },
        ),
        migrations.CreateModel(
            name='CourseConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'مشاور دوره',
                'verbose_name_plural': 'مشاوران دوره',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.conversation', verbose_name='گفتگو')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان ها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=255, verbose_name='کد پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict, verbose_name='دسترسی ها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل دسترسی',
                'verbose_name_plural': 'پروفایل های دسترسی',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100, verbose_name='پایه تحصیلی')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='داوطلب')),
            ],
            options={
                'verbose_name': 'پروفایل داوطلب',
                'verbose_name_plural': 'پروفایل داوطلبان',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان برنامه')),
                ('week_start', models.DateField(verbose_name='شروع هفته')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='داوطلب')),
            ],
            options={
                'verbose_name': 'برنامه مطالعاتی',
                'verbose_name_plural': 'برنامه های مطالعاتی',
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فعالیت')),
                ('study_date', models.DateField(verbose_name='تاریخ')),
                ('estimated_minutes', models.PositiveIntegerField(verbose_name='زمان پیشنهادی')),
                ('status', models.CharField(choices=[('pending', 'انجام نشده'), ('done', 'انجام شده'), ('failed', 'انجام نشده توسط داوطلب')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.studyplan', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'باکس برنامه',
                'verbose_name_plural': 'باکس های برنامه',
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='گزینه')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.survey', verbose_name='نظرسنجی')),
            ],
            options={
                'verbose_name': 'گزینه نظرسنجی',
                'verbose_name_plural': 'گزینه های نظرسنجی',
            },
        ),
    ]
