# Generated by Django 6.0.5 on 2026-06-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_delete_news_remove_notification_user_delete_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='max_students',
            field=models.PositiveIntegerField(verbose_name='حداکثر ظرفیت داوطلب'),
        ),
    ]
