# Generated by Django 6.0.5 on 2026-06-26 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_consultantprofile_max_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
    ]
