# Generated by Django 6.0.5 on 2026-06-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_consultantprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ConsultantProfile',
        ),
        migrations.DeleteModel(
            name='PermissionProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
