# Generated by Django 6.0.5 on 2026-07-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_permissionprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultingrequest',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='consultingrequest',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='consultingrequest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='consultingrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsultantSchedule',
        ),
        migrations.DeleteModel(
            name='ConsultingService',
        ),
        migrations.DeleteModel(
            name='ConsultingRequest',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
